### ISSUE TITLE
problem about tensor2tensor

### ISSUE THREAD

**Issue by JinHeap** [yanghoonkim/attnconvnet#1]
I try to run your project with python 2.7.
Because conda cann't install tensor2tensor ,i used pip to install it.
when tensorflow=1.4.1,Error is ImportError: cannot import name control_flow_util.
when i update tensorflow to 1.10,Error is ImportError: cannot import name common_layers.
I think there some problem about tensor2tensor and tensoflow version.
Thanks.

**Comment by yanghoonkim** [comment]
Hi,

I forgot specifying the version of tensor2tensor.
You can solve the error with the tensor2tensor version of 1.0.8 which is a quite old version.

**Comment by JinHeap** [comment]
It's work.Thanks

**Comment by JinHeap** [comment]
the common_layers.py is  the same to the file in tensor2tenor or there were some place you change in your project.
I think is the same lib.
I can use tensor2tensor to replaced the file model.py import common_xx by 
```python
# import common_attention as ca
# import common_layers as cl
from tensor2tensor.layers import common_attention as ca
from tensor2tensor.layers import common_layers as cl
